### ISSUE TITLE
Update Group Creator screen

### ISSUE THREAD

**Issue by jde** [coralproject/design#6]
- [ ] Add the ability to save a description

**Comment by egrdina** [comment]
![save group group page](https://cloud.githubusercontent.com/assets/7856099/13679756/62bbe808-e6c3-11e5-82a2-5447fffe0f2b.jpg)

**Comment by egrdina** [comment]
![screen shot 2016-03-23 at 1 13 49 pm](https://cloud.githubusercontent.com/assets/7856099/14049465/e62cad7a-f28b-11e5-8d10-6041067fc47f.png)

**Comment by jde** [comment]
@emmagrdina: Looking very clean.  2 notes:
1) More datapoints on the user cards + a sort feature.  We have a ticket open to show the datapoints that the fields that are selected in the filters.  For example, if the group is based on total comments and reply ratio, those two datapoints should be on the cards and the list should be sortable by those.
2) We need a more compact way of showing the filters.  The current set already go way off the bottom of the page and more will be added.  A few ideas that have been tossed around: categorize the filters and make an accordion menu, do something with tags, have a way of showing some filters based on your intent (aka, we can decide that filters x, y and z are good for trolls and only show those for a certain “Category” of group.)
